params:
  device: cuda:0
  category: bottle
  height: 224
  width: 224
  cross_validation: 0
  batch_size: 4
  num_embedding: 550
  tracking_uri: file:///dgx/github/PaDiM/padim/mlruns
  experiment_name: mvtec
  run_name: ${params.category}_cv${params.cross_validation}

model:
  name: padim.models - WideResNet50
  args:

transforms:
  train:
    - name: albumentations - Resize
      args:
        height: ${params.height}
        width: ${params.width}
        p: 1
    - name: albumentations - Normalize
      args:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        p: 1
    - name: albumentations.pytorch - ToTensorV2
      args:
        p: 1
  test:
    - name: albumentations - Resize
      args:
        height: ${params.height}
        width: ${params.width}
        p: 1
    - name: albumentations - Normalize
      args:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        p: 1
    - name: albumentations.pytorch - ToTensorV2
      args:
        p: 1

datasets:
  train:
    name: padim.datasets - MVTecDataset
    args:
      data_dir: /dgx/github/RIAD/data
      query_list:
        - cv${params.cross_validation}=='train' & category=='${params.category}'
        - cv${params.cross_validation}=='val' & category=='${params.category}'
      debug: False
  test:
    name: padim.datasets - MVTecDataset
    args:
      data_dir: /dgx/github/RIAD/data
      query_list:
        - cv${params.cross_validation}=='test' & category=='${params.category}'
      debug: false

dataloaders:
  train:
    name: torch.utils.data - DataLoader
    args:
      batch_size: ${params.batch_size}
      num_workers: ${params.batch_size}
      pin_memory: True
      shuffle: True
  test:
    name: torch.utils.data - DataLoader
    args:
      batch_size: ${params.batch_size}
      num_workers: ${params.batch_size}
      pin_memory: True
      shuffle: True
