name: black

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -U black hacking isort mypy blackdoc
      - name: black
        run: black . --check --diff
