name: build-image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-image:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker login
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Docker build and push
      uses: docker/build-push-action@v2
      with:
        file: docker/Dockerfile
        push: true
        tags: taikiinoue45/mvtec:padim
