name: merge

on:
  push:
    branches: [main]

jobs:
  docker-build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          push: true
          tags: taikiinoue45/mvtec:padim

  pytest:
    needs: [docker-build-and-push]
    runs-on: self-hosted
    container:
      image: taikiinoue45/mvtec:padim

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run chmod
        run: chmod -R 777 ./
        if: always()

      - name: Run experiments
        run: |
          python run.py params.category=bottle
          python run.py params.category=cable
          python run.py params.category=capsule
          python run.py params.category=carpet
          python run.py params.category=grid
          python run.py params.category=hazelnut
          python run.py params.category=leather
          python run.py params.category=metal_nut
          python run.py params.category=pill
          python run.py params.category=screw
          python run.py params.category=tile
          python run.py params.category=toothbrush
          python run.py params.category=transistor
          python run.py params.category=wood
          python run.py params.category=zipper
