name: pull_request

on:
  pull_request:
    branches: [main]

jobs:
  docker-build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          push: false
          tags: taikiinoue45/mvtec:padim
          no-cache: true

      - name: Clean up
        if: always()
        run: ls -A1 | xargs rm -rf

  pytest:
    needs: [docker-build]
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker run
        run: docker run -it --rm taikiinoue45/mvtec:padim /bin/bash

      - name: Run pytest
        run: pytest -v --cov=padim --cov-report=xml tests/test_run.py

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          name: PaDiM
          fail_ci_if_error: true

      - name: Clean up
        if: always()
        run: ls -A1 | xargs rm -rf
