name: pull-requests

on:
  pull_request:
    branches: [main]

jobs:
  docker-build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker build
      uses: docker/build-push-action@v2
      with:
        file: docker/Dockerfile
        push: false
        tags: taikiinoue45/mvtec:padim

  pytest:
    needs: [docker-build]
    runs-on: self-hosted
    container:
      image: taikiinoue45/mvtec:padim

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run chmod
      run: chmod -R 777 ./
      if: always()

    - name: Run pytest
      run: pytest -v --cov="."
      working-directory: ./tests
