name: run-experiments

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

  run-experiments:
    needs: checkout
    runs-on: self-hosted
    container:
      image: taikiinoue45/mvtec:padim

    steps:
    - name: ls
      run: ls

    - name: Check GPU status
      run: nvidia-smi


